/*
 * event.h
 *
 *  Created on: 26 janv. 2021
 *      Author: stephane
 */

#include "factory_io.h"

#ifndef APP_INC_EVENT_H_
#define APP_INC_EVENT_H_


// ACTUATORS
#define ACTUATORS_OFF (0x00000000)

#define BLOCAGE_ENTREE_PALETISEUR_ON (0x00000001 << 2U)
#define BLOCAGE_ENTREE_PALETISEUR_msk BLOCAGE_ENTREE_PALETISEUR_ON

#define PORTE_ON (0x00000001 << 3U)
#define PORTE_msk PORTE_ON

#define POUSSOIR_ON (0x00000001 << 4U)
#define POUSSOIR_msk POUSSOIR_ON

#define CLAMP_ON (0x00000001 << 5U)
#define CLAMP_msk CLAMP_ON

#define MONTER_ASCENSSEUR_ON (0x00000001 << 6U)
#define MONTER_ASCENSSEUR_msk MONTER_ASCENSSEUR_ON

#define DESCENDRE_ASCENSSEUR_ON (0x00000001 << 8U)
#define DESCENDRE_ASCENSSEUR_msk DESCENDRE_ASCENSSEUR_ON

#define ASCENSSEUR_TO_LIMIT_ON (0x00000001 << 9U)
#define ASCENSSEUR_TO_LIMIT_msk ASCENSSEUR_TO_LIMIT_ON

#define DISTRIBUTION_PALETTE_ON (0x00000001 << 10U)
#define DISTRIBUTION_PALETTE_msk DISTRIBUTION_PALETTE_ON

#define CHARGER_PALETTE_ON (0x00000001 << 11U)
#define CHARGER_PALETTE_msk CHARGER_PALETTE_ON


//SENSOR
#define SENSOR_OFF (0x00000000)

#define ENTREE_PALETISEUR_msk (0x00000001 << 2U)
#define ENTREE_PALETISEUR_ON SENSOR_OFF
#define ENTREE_PALETISEUR_OFF ENTREE_PALETISEUR_msk

#define PORTE_OUVERTE_msk (0x00000001 << 3U)
#define PORTE_OUVERTE_ON PORTE_OUVERTE_msk
#define PORTE_OUVERTE_OFF SENSOR_OFF

#define ASCENSSEUR_ETAGE_RDC_msk (0x00000001 << 6U)
#define ASCENSSEUR_ETAGE_RDC_ON ASCENSSEUR_ETAGE_RDC_msk
#define ASCENSSEUR_ETAGE_RDC_OFF SENSOR_OFF

#define ASCENSSEUR_ETAGE_1_msk (0x00000001 << 8U)
#define ASCENSSEUR_ETAGE_1_ON ASCENSSEUR_ETAGE_1_msk
#define ASCENSSEUR_ETAGE_1_OFF SENSOR_OFF

#define SORTIE_PALETTE_msk (0x00000001 << 10U)
#define SORTIE_PALETTE_ON SORTIE_PALETTE_msk
#define SORTIE_PALETTE_OFF SENSOR_OFF

#define ENTRE_PALETTE_msk (0x00000001 << 13U)
#define ENTRE_PALETTE_ON ENTRE_PALETTE_msk
#define ENTRE_PALETTE_OFF SENSOR_OFF

#define PALETTE_DISTRIBUEE_msk (0x00000001 << 16U)
#define PALETTE_DISTRIBUEE_OFF PALETTE_DISTRIBUEE_msk
#define PALETTE_DISTRIBUEE_ON SENSOR_OFF


#endif /* APP_INC_EVENT_H_ */
